from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 453)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.nQ = QtWidgets.QLineEdit(self.centralwidget)
        self.nQ.setGeometry(QtCore.QRect(140, 20, 121, 21))
        self.nQ.setObjectName("nQ")
        self.btnCargarTabla = QtWidgets.QPushButton(self.centralwidget)
        self.btnCargarTabla.setGeometry(QtCore.QRect(10, 50, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnCargarTabla.setFont(font)
        self.btnCargarTabla.setObjectName("btnCargarTabla")
        self.tabla = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla.setEnabled(True)
        self.tabla.setGeometry(QtCore.QRect(10, 120, 251, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabla.sizePolicy().hasHeightForWidth())
        self.tabla.setSizePolicy(sizePolicy)
        self.tabla.setMouseTracking(False)
        self.tabla.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabla.setAutoFillBackground(False)
        self.tabla.setAutoScroll(True)
        self.tabla.setDragEnabled(False)
        self.tabla.setShowGrid(True)
        self.tabla.setWordWrap(True)
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(2)
        self.tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(1, item)
        self.tabla.horizontalHeader().setVisible(True)
        self.tabla.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla.horizontalHeader().setHighlightSections(False)
        self.tabla.horizontalHeader().setMinimumSectionSize(39)
        self.tabla.horizontalHeader().setSortIndicatorShown(False)
        self.tabla.horizontalHeader().setStretchLastSection(True)
        self.tabla.verticalHeader().setStretchLastSection(False)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(740, 60, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 60, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.campoQ0 = QtWidgets.QLineEdit(self.centralwidget)
        self.campoQ0.setGeometry(QtCore.QRect(300, 60, 61, 21))
        self.campoQ0.setText("")
        self.campoQ0.setObjectName("campoQ0")
        self.campoF = QtWidgets.QLineEdit(self.centralwidget)
        self.campoF.setGeometry(QtCore.QRect(410, 60, 61, 21))
        self.campoF.setObjectName("campoF")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(380, 60, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btnCalcularCadena = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcularCadena.setGeometry(QtCore.QRect(140, 50, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnCalcularCadena.setFont(font)
        self.btnCalcularCadena.setObjectName("btnCalcularCadena")
        self.btnLimpiar = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpiar.setGeometry(QtCore.QRect(10, 380, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnLimpiar.setFont(font)
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(550, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.tabla_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_2.setEnabled(True)
        self.tabla_2.setGeometry(QtCore.QRect(270, 120, 321, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabla_2.sizePolicy().hasHeightForWidth())
        self.tabla_2.setSizePolicy(sizePolicy)
        self.tabla_2.setMouseTracking(False)
        self.tabla_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabla_2.setAutoFillBackground(False)
        self.tabla_2.setAutoScroll(True)
        self.tabla_2.setDragEnabled(False)
        self.tabla_2.setShowGrid(True)
        self.tabla_2.setWordWrap(True)
        self.tabla_2.setObjectName("tabla_2")
        self.tabla_2.setColumnCount(2)
        self.tabla_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_2.setHorizontalHeaderItem(1, item)
        self.tabla_2.horizontalHeader().setVisible(True)
        self.tabla_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_2.horizontalHeader().setHighlightSections(False)
        self.tabla_2.horizontalHeader().setMinimumSectionSize(39)
        self.tabla_2.horizontalHeader().setSortIndicatorShown(False)
        self.tabla_2.horizontalHeader().setStretchLastSection(True)
        self.tabla_2.verticalHeader().setStretchLastSection(False)
        self.tabla_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_3.setEnabled(True)
        self.tabla_3.setGeometry(QtCore.QRect(600, 120, 221, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabla_3.sizePolicy().hasHeightForWidth())
        self.tabla_3.setSizePolicy(sizePolicy)
        self.tabla_3.setMouseTracking(False)
        self.tabla_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabla_3.setAutoFillBackground(False)
        self.tabla_3.setAutoScroll(True)
        self.tabla_3.setDragEnabled(False)
        self.tabla_3.setShowGrid(True)
        self.tabla_3.setWordWrap(True)
        self.tabla_3.setObjectName("tabla_3")
        self.tabla_3.setColumnCount(2)
        self.tabla_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_3.setHorizontalHeaderItem(1, item)
        self.tabla_3.horizontalHeader().setVisible(True)
        self.tabla_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_3.horizontalHeader().setHighlightSections(False)
        self.tabla_3.horizontalHeader().setMinimumSectionSize(39)
        self.tabla_3.horizontalHeader().setSortIndicatorShown(False)
        self.tabla_3.horizontalHeader().setStretchLastSection(True)
        self.tabla_3.verticalHeader().setStretchLastSection(False)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 251, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(270, 90, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(600, 90, 221, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lb_resultados_qR = QtWidgets.QLabel(self.centralwidget)
        self.lb_resultados_qR.setGeometry(QtCore.QRect(270, 380, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_resultados_qR.setFont(font)
        self.lb_resultados_qR.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_resultados_qR.setObjectName("lb_resultados_qR")
        self.lb_resultados_F = QtWidgets.QLabel(self.centralwidget)
        self.lb_resultados_F.setGeometry(QtCore.QRect(600, 380, 221, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_resultados_F.setFont(font)
        self.lb_resultados_F.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_resultados_F.setObjectName("lb_resultados_F")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Conversión AFN a AFD"))
        self.label_2.setText(_translate("MainWindow", "Asignar Q (0 - n):"))
        self.btnCargarTabla.setText(_translate("MainWindow", "CARGAR"))
        self.tabla.setSortingEnabled(False)
        item = self.tabla.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "E = { 0, 1 }"))
        self.label_4.setText(_translate("MainWindow", "Q0 ="))
        self.label_5.setText(_translate("MainWindow", "F = "))
        self.btnCalcularCadena.setText(_translate("MainWindow", "CALCULAR"))
        self.btnLimpiar.setText(_translate("MainWindow", "LIMPIAR"))
        self.label_8.setText(_translate("MainWindow", ""))
        self.tabla_2.setSortingEnabled(False)
        item = self.tabla_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        self.tabla_3.setSortingEnabled(False)
        item = self.tabla_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        self.label_9.setText(_translate("MainWindow", "Q\'s"))
        self.label_10.setText(_translate("MainWindow", "δ\'"))
        self.label_11.setText(_translate("MainWindow", "r\'"))
        self.lb_resultados_qR.setText(_translate("MainWindow", "Q\' = ..."))
        self.lb_resultados_F.setText(_translate("MainWindow", "F\' = ..."))
